# Generated by Django 5.0.1 on 2024-02-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('pressure', models.FloatField()),
                ('rainPossibility', models.BooleanField(default=False)),
                ('amountOfRain', models.IntegerField(default=0)),
                ('description', models.TextField()),
            ],
        ),
    ]
