# Generated by Django 5.0.1 on 2024-02-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='cityName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
