# Generated by Django 5.0.1 on 2024-02-23 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_alter_weather_cityname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=100, unique=True)),
                ('a_age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=100, unique=True)),
                ('b_name', models.CharField(max_length=100, unique=True)),
                ('author_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.author')),
            ],
        ),
    ]
