# Generated by Django 5.0.1 on 2024-02-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_author_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='image_path',
            field=models.CharField(default='/static/uploads/empty.jpg', max_length=1000),
        ),
        migrations.AddField(
            model_name='weather',
            name='images',
            field=models.FileField(null=True, upload_to='static/uploads/'),
        ),
    ]
