# Generated by Django 5.0.1 on 2024-02-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_weather_image_path_weather_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='image_path',
            field=models.CharField(default='/uploads/empty.jpg', max_length=1000),
        ),
        migrations.AlterField(
            model_name='weather',
            name='images',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
